# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7767fc4914c7f43cd9dd83250c2caad6"
name = "record-loft-order-management"
application_url = "https://record-loft-order-management.netlify.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products, read_orders, read_customers, read_fulfillments, read_merchant_managed_fulfillment_orders, read_assigned_fulfillment_orders, read_third_party_fulfillment_orders"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[auth]
redirect_urls = [
  "https://record-loft-order-management.netlify.app/auth/callback",
  "https://record-loft-order-management.netlify.app/auth/shopify/callback",
  "https://record-loft-order-management.netlify.app/api/auth/callback"
]

[build]
automatically_update_urls_on_dev = true
