name: Deploy to Netlify

on:
  push:
    branches:
      - main # Change to 'master' if your default branch is named master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Generate Prisma Client
        run: yarn prisma generate

      - name: Deploy to Netlify
        run: |
          sudo yarn global add netlify-cli
          export PATH="$(yarn global bin):$PATH"
          netlify deploy --prod --build --auth=${{ secrets.NETLIFY_AUTH_TOKEN }} --site=${{ secrets.NETLIFY_SITE_ID }}
